stages:
  - build
  - release

build_untagged:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG == null"
  image: maven:3.8.1-openjdk-16
  script: mvn clean package
  artifacts:
    name: "BoxedVillagers"
    paths:
    - "target/*.jar"
    exclude:
      - "target/original*.jar"

build_tagged:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG != null"
  image: maven:3.8.1-openjdk-16
  before_script:
    - echo "JOB=$CI_JOB_ID" >> build.env
  script: mvn -Drevision="$CI_COMMIT_TAG" clean package
  artifacts:
    name: "BoxedVillagers"
    expire_in: never
    paths:
    - "target/*.jar"
    exclude:
      - "target/original*.jar"
    reports:
      dotenv: build.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "Creating Release"
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build_tagged
      artifacts: true
  release:
    name: "Boxed Villagers $CI_COMMIT_TAG"
    tag_name: $CI_COMMIT_TAG
    description: "Automatically Generated Release"
    assets:
      links:
        - name: "Plugin JAR"
          url: "https://gitlab.com/eggmc/boxedvillagers/-/jobs/${JOB}/artifacts/file/target/BoxedVillagers-$CI_COMMIT_TAG.jar"