### Technical
# Which world should be taken as a reference for timing boxed villager restocks. Make sure this is a world with a day-night cycle that is loaded at all times, ideally your main world.
timeWorld: world

# If no currency name is found by Vault, use this symbol instead
fallbackCurrencySymbol: ""

### Balance
# Minimum amount of slots a villager has on capture. If the villager has more trades unlocked than this setting, the number of trades will take priority.
minTradeSlots: 0

# Maximum amount of unlockable trade slots. Caps at 27.
maxTradeSlots: 27

# Maximum amount of permitted cures. Caps at 7.
maxCures: 7

# Minimum and maximum XP rewards for trading. Awarded per trade regardless of the trade content. Vanilla values are 3-6 by default and 8-11 for villagers willing to breed.
minXPReward: 3
maxXPReward: 6

### Costs
# For any list that would be empty, use "FREE: 0" instead, the plugin needs to be a value for each entry to read it, otherwise things will break
# You can also add non-item costs, currently supported is MONEY, add it like an item cost

# Cost for buying a villager scroll
scrollCost:
  FREE: 0

# Cost for purging (permanently removing) a trade
purgeCost:
  FREE: 0

# Cost for extracting a trade
extractCost:
  FREE: 0

# Cost for adding an extracted trade onto another villager
addCost:
  FREE: 0

# Cost for curing a boxed villager
cureCost:
  1:
    FREE: 0
  2:
    FREE: 0
  3:
    FREE: 0
  4:
    FREE: 0
  5:
    FREE: 0
  6:
    FREE: 0
  7:
    FREE: 0

# Cost for adding a trade slot
slotCost:
  1:
    FREE: 0
  2:
    FREE: 0
  3:
    FREE: 0
  4:
    FREE: 0
  5:
    FREE: 0
  6:
    FREE: 0
  7:
    FREE: 0
  8:
    FREE: 0
  9:
    FREE: 0
  10:
    FREE: 0
  11:
    FREE: 0
  12:
    FREE: 0
  13:
    FREE: 0
  14:
    FREE: 0
  15:
    FREE: 0
  16:
    FREE: 0
  17:
    FREE: 0
  18:
    FREE: 0
  19:
    FREE: 0
  20:
    FREE: 0
  21:
    FREE: 0
  22:
    FREE: 0
  23:
    FREE: 0
  24:
    FREE: 0
  25:
    FREE: 0
  26:
    FREE: 0
  27:
    FREE: 0


### Help Pages
# How many standard characters a help page should be wide, large values may break for players with narrow chat.
helpWidth: 50

# Help pages, use \n to force line breaks. Both vanilla formatting and color codes work, but do not carry over line breaks, be sure to test.
# To see which color codes are available, look into strings.yml.
helpPages:
  default:
    title: "Boxed Villagers Help Pages"
    content: "Boxed Villagers is a plugin that allows converting villagers into items, which can be traded with. This lightens the server load by taking away the stress caused by large trading halls and benefits the player by providing reliably restocking trades."