name: BoxedVillagers
version: 1.0.0
main: io.gitlab.arkdirfe.boxedvillagers.BoxedVillagers
author: Arkdirfe
api-version: 1.17
depend: [NBTAPI]
softdepend: [Vault]
commands:
  boxedvillagers:
    description: Main Command
    usage: "Usage: /boxedvillagers help"
    aliases: bv
  witchdoctor:
    description: Opens the Witch Doctor UI that handles upgrading and changing boxed villagers
    usage: "Usage: /witchdoctor"
    aliases: wd

permissions:
  boxedvillagers.*:
    description: Access to all permissions
    children:
      boxedvillagers.witchdoctor: true
      boxedvillagers.witchdoctor.advanced: true
      boxedvillagers.witchdoctor.extract: true
      boxedvillagers.admin: true
  boxedvillagers.witchdoctor:
    description: /witchdoctor permission
    default: true
  boxedvillagers.witchdoctor.advanced:
    description: Allows rearranging and purging of trades in the witchdoctor UI
    default: op
  boxedvillagers.witchdoctor.extract:
    description: Allows extracting and re-inserting of trades in the witchdoctor UI
    default: op
  boxedvillagers.admin:
    description: Allows use of /bv give and /bv cure and allows opening of the witchdoctor ui in admin mode (with costs disabled)
    default: op